# this recipe packages the shared libraries from the conda-builder docker image.  It does not compile anything, just
#     copies files that are installed in the docker image.  It should only be built from the docker image.

package:
  name: libgcc
  version: 5.2.0

about:
  home: http://gcc.gnu.org/
  license: GPL
  license_family: GPL3
  summary: libstdc++, libgcc_s, and libgfortran for the conda-builder docker image
