
package:
    name: mongodb
    version: 3.2.0

source:
    git_tag: r3.2.0
    git_url: https://github.com/mongodb/mongo

build:
    number: 0

requirements:
    build:
        - python
        - scons
        - openssl

    run:
        - openssl

about:
    home: http://www.mongodb.org/
    license: AGPL-3 Apache-2.0

